### ISSUE TITLE
TPC: Predictive and Auxiliary input validation bug

### ISSUE THREAD

**Issue by FlaviusRaducu** [ONSdigital/sml-python-small#80]
# Description

According to JIRA ticket SPP-12070 and the TPC input spec [here](https://github.com/ONSdigital/Statistical-Method-Specifications/blob/main/editing_and_imputation/editing/thousand_pounds_correction/technical_specification.md#41-input-records); predictive and auxiliary `None` values should be valid inputs for the method.

## Existing behaviour
The following exception is thrown when both the predictive and auxiliary are null; the code is [here](https://github.com/ONSdigital/sml-python-small/blob/main/sml_small/editing/thousand_pounds/thousand_pounds.py#L374)
`Exception: ('identifier: 40', ValueError('one of predictive or auxiliary must be specified'))`

## Expected behaviour
As it can be observed in SPP-12070 and TPC spec, the method users expect that given an input payload with both predictive and auxiliary None, the method should stop and return an 'S' marker. Looking briefly at the code it seems like the [check_zero_error](https://github.com/ONSdigital/sml-python-small/blob/main/sml_small/editing/thousand_pounds/thousand_pounds.py#L397) procedure should be able to handle this behaviour.

**Comment by gibbardsteve** [comment]
The method specification says the following:
Although predicted and auxiliary are both optional, at least one must be provided for the method to work. Else the method will not run.

This was a requirement from MQD

**Comment by FlaviusRaducu** [comment]
hm, I see; I missed that, my bad. I will close the issue then since for the purpose of SPP-12070 I can always have predicted as 0 when both are None
